### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by demhademha**
• use **sbreload** over **killall  SpringBoard**
* Fix various grammatical and spelling mistakes.

### CODE REVIEW

**Comment by demhademha** [comment]
You might want to enable issues for this repo, currently they are disabled

**Comment by Yaya48** [comment]
> You might want to enable issues for this repo, currently they are disabled

I’d just comment that shouldn’t be used at all it’s mostly broken and this is very old version the installation method is also crap anyways at that point just use chimera/odyssey

**Comment by demhademha** [comment]
Shall I close this pull request?

**Comment by Yaya48** [comment]
> Shall I close this pull request?

Well i don't think this gonna get merged.

**Comment by jayguar1206** [comment]
As Yaya48 has mentioned, just use Odyssey/Chimera honestly. This fork is quite old and I doubt your pull request will fix it.

**Pull request closed without merging**
